# -*- coding: utf-8 -*-
__version__ = '5.9.5'
APP_NAME = 'SQM 재고관리 시스템'
APP_NAME_EN = 'SQM Inventory Management System'
VERSION_HISTORY = {
    '5.9.5': '📋 v5.9.5: Allocation UI — 출고 예약 다이얼로그(파일업로드→파싱→미리보기→예약→출고→확정), 예약 현황 조회, 메뉴 연동',
    '5.9.4': '🏗️ v5.9.4: 구조 리팩토링 — 대형 파일 Mixin 분할(onestop_inbound/database), COLUMN_REGISTRY 도입(Round-trip 보장), core.config Facade 검증',
    '5.9.3': '🚀 v5.9.3: 출고/반품 로직 강화 — RESERVED 상태 추가, allocation_plan 테이블, Allocation 파서 안정화(과학표기법/Total행/GW), 반품 SOLD/RESERVED 지원',
    '5.9.2': '🧹 v5.9.2: P2 코드 위생 — except+pass 로깅 전환(11파일), bare except 제거, DB경로 통일, re.compile 모듈레벨 이동, 미사용 import 정리',
    '5.9.1': '🐛 v5.9.1: P0 크래시 버그 9건 수정, P1 릴리스 위생, 샘플 UID S0→0, 트리뷰 폰트 축소(14→11pt), 컨테이너 구분 버튼 필터바 이동, Excel round-trip 컬럼 매칭 수정',
    '5.9.0': '📄 v5.9.0: PDF/이미지 변환 통합 — 캡처 이미지(PNG/JPG/BMP/TIFF) → Excel/Word 변환 지원, 일괄 변환 이미지 포함, D/O 파싱 하이브리드(Arrival Date+Free Time), Gemini thinking model 대응, 입고 엔진·드래그앤드롭·테마·키바인딩 개선',
    '5.8.9': '🎯 v5.8.9: 원스톱 입고 한 화면 처리(업로드2 제거)·파싱 실시간 미리보기·DateEntry gui_bootstrap 통일·Location 엑셀 양식2 UID 컬럼 지원',
    '5.8.8': '🎨 v5.8.8: UI Phase3·Phase4 — 8px 그리드(Spacing)·폰트 3단계(FontScale), 다이얼로그 크기 표준화(DialogSize·center_dialog)',
    '5.8.7': '🎨 v5.8.7: UI 마스터 플랜·Phase1/2 적용 — 기본 컬럼 8개, 트리뷰 36px·제브라, 색상 팔레트(ThemeColors) 통일, 톤백 SAP NO 접미사 제거 표시 (※이전 v8.7.0 푸시는 버전 표기 오류)',
    '5.8.6.2': '🧪 v5.8.6.2: P5-8~14 단위테스트 (core types/validators/formatters/constants/config, run_bootstrap, config_logging, file_utils), 전체 수집 순환참조 방지·engine_modules None 방어',
    '5.8.6.1': '🔧 v5.8.6.1: P5-5·P5-7 적용 (config→core.config 전환, helpers/safe_utils→core.types), get_settings 추가, core.types 순환참조 제거',
    '5.8.6': '🏗️ v5.8.6: P5-1~4 점진적 core 전환 (config 보강, types/constants/validators → core)',
    '5.8.5': '🎨 v5.8.5: 샘플 톤백 No 표기 S → S0 (숫자와 혼동 방지)',
    '5.8.3': '🏗️ v5.8.3: P4 완료 — core/ 공통 라이브러리 파사드(types, validators, formatters, constants, config, config_logging)',
    '5.8.2': '🏗️ v5.8.2: P3 완료 — run.py 슬림화(run_bootstrap 분리), 진입점 100줄 이하',
    '5.8.1': '🏗️ v5.8.1: P2 완료 — config 분할(config_logging, utils/file_utils), gui_bootstrap, 루트 migrate 삭제',
    '5.8.0': '🏗️ v5.8.0: P1 완료 — validate_lot_no/validate_sap_no 단일 소스(validators), format_*/find_column 단일 소스(formatters)',
    '5.7.9': '🔧 v5.7.9: 엔트리 run.py 통일, P0 완료(run.bat 삭제·SQM_실행.bat), 리팩토링 마스터 플랜 문서',
    '5.7.8': '🏗️ v5.7.8: 출고 전 필수 — 샘플 1kg 상수화, 상태 상수(PICKED/SOLD), constants·safe_float·config_sql 분할',
    '5.7.7': '🔖 v5.7.7: 릴리스 태그',
    '5.7.6': '🐛 v5.7.6: 출고 API 디버깅 — import_handlers process_outbound(allocation_data) 시그니처 통일, LOT 전량 출고 시 current_weight 조회',
    '5.7.5': '🎨 v5.7.5: UI·원스톱 입고 개선 — 폰트 위계, 기간 캘린더, 진행 팝업, Invoice/FA·Bill of Lading·Delivery Order, UID 표시, 스탯바 None 수정',
    '5.7.4': '🐛 v5.7.4: 표시 컬럼 체크 해제 시 Invalid column index #all 수정 — 재고/톤백 리스트 공통 (displaycolumns #all 정규화)',
    '5.7.3': '🐛 v5.7.3: Excel 입고 — add_inventory_from_dict 추가 (CRUDMixin), GUI tonbags 호환',
    '5.7.2': '🔧 v5.7.2: 크로스 검증 샘플 포함 합산 — 정합성 경고 0건 (5001=500×10+1)',
    '5.7.1': '🐛 v5.7.1: 톤백 무게 정합성 — per_bag=(총무게-1)/톤백수 주석 강화, NET/Balance/Inbound 톤백 개별 무게만 사용',
    '5.7.0': '📥 v5.7.0: 입고 Gate-1 강화 — PL+FA+BL 필수 3종 없으면 DB 업로드 차단, D/O 후속 연결 정책 명확화',
    '5.6.9': '🎨 v5.6.9: 로케이션 엑셀 양식 확정, 다크 테마 가시성, LOT 상세/하단 요약 스타일 통일, Avail 동적 로직 명시',
    '5.6.8': '🏗️ v5.6.8: 상수파일 분리 + 핵심 테스트 11개 + 데드테이블 마킹 + 타입힌트 보강',
    '5.6.7': '🧹 v5.6.7: DO 후속 연결 + 데드코드 제거(inbound_preview/PG/picking_parser/-1,583줄) + unused import 정리 + 루트 md 정리',
    '5.6.6': '🔧 v5.6.6: 변수 통일 — bag_count→mxbg_pallet, invoice_no→salar_invoice_no, total_weight_kg→net_weight + 입고경로 단일화',
    '5.6.0': '🔴 v5.6.0: R1~R6완료 — 대원칙정합성, SQL보안, MAC잠금, except→0, print→logger, messagebox통일, 잔여톤백Avail컬럼, 심플엑셀출고',
    '5.5.5': '🔧 v5.5.5: 코드감사(-9,244줄/15.8%), 죽은코드 대량제거, except→logger.debug(43건), 샘플S00통일, 보고서메뉴, DB문서화',
    '5.5.3': '🔧 v5.5.3: UI간소화(tk→ttk), Excel 6옵션, 죽은코드 -5,474줄, 메뉴재배치, 샘플S00통일, 📝보고서메뉴, DB문서화',
    '5.5.2': '🔧 v5.5.2: PL 디버깅 강화 — 원문 저장 토글, JSON 추출/검증 로그, 프롬프트 강제 스키마, OpenAI 폴백 옵션',
    '5.5.1': '🔒 v5.5.1: 모든 문서 파싱을 Gemini API로 강제(폴백 제거) + API Key 미설정 시 하드스톱',
    '5.5.0': '🧩 v5.5.0: (적용본) UI/로직 개선 누적 반영',
    '5.4.2': '🔧 v5.4.2: 탭색상 테마동기화 + API메뉴 복원 + Excel 18컬럼 + Treeview 글씨색 + 통계합계 수정',
    '5.4.1': '🔧 v5.4.1: 드롭다운 메뉴 테마 동기화',
    '5.2.0': '🏗️ v5.2.0 재구축: 샘플 하드스톱 + tonbag_no TEXT + (BL,LOT,tonbag_no) 유니크 + 데드코드 정리',
    '5.1.5': '🛡️ 반품/분할/병합 강화 (이전 빌드)',
    '5.1.4': '🛡️ 입출고 정합성 게이트: 트랜잭션 안에서 즉시 검증 → 불일치 시 자동 롤백',
    '5.1.3': '🔄 트랜잭션 컨텍스트 매니저 적용: 입고/위치업로드/문서업데이트 5곳 전환',
    '5.1.2': '🔁 트랜잭션 재시도 강화: BEGIN IMMEDIATE 재시도 + with db.transaction() 컨텍스트 매니저',
    '5.1.1': '🔍 에러 로깅 강화: 침묵 except+pass 37건 → logger.debug/warning 변환',
    '5.1.0': '🔄 용어 통일: sub_lt→tonbag_no, sold_to→customer, mxbg_pallet→tonbag_count 호환 레이어',
    '5.0.9': '🔧 메뉴 색상 복구 수정 + 출고 샘플/톤백 정확한 구분 + 미리보기 레이아웃 개선',
    '5.0.8': '✅ 톤백 리스트 완전 통일: 재고 리스트와 동일한 포맷',
    '5.0.7': '🎨 대시보드 콤팩트화: 폰트/패딩/높이 축소로 깔끔하게',
    '5.0.6': '🔧 긴급 수정: 컬럼 ID 불일치, StatusBar, tk_popup 방식',
    '5.0.5': '🔧 메뉴 버튼 색상 문제 근본 해결 + import 오류 수정',
    '5.0.4': '🐛 핫픽스: SyntaxError 완전 수정',
    '5.0.3': '🔧 자동 백업 강화 + 성능 최적화: 백업 검증, 자동 복구, 쿼리 캐싱',
    '5.0.2': '🎯 사용성 개선: 메뉴 간소화 + 버튼 색상 수정 (Phase 1 완료)',
    '5.0.1': '🔧 긴급 수정: sqlite3.Row.get() 에러 완전 해결',
    '5.0.0': '🎯 완전 통일 버전: 모든 UI 100% 통일',
}
def get_version(): return __version__
def get_version_info(): return f"SQM v{__version__}"
__all__ = ['__version__', 'APP_NAME', 'APP_NAME_EN', 'VERSION_HISTORY', 'get_version', 'get_version_info']
