# -*- coding: utf-8 -*-
"""SQM 재고관리 시스템 — 버전 정보"""

__version__ = "8.0.9"
APP_NAME    = "SQM 재고관리 시스템"
BUILD_DATE  = "2026-03-20"
BUILD_NOTE  = (
    "v8.0.9 (2026-03-20)\n"
    "\n"
    "[파싱 엔진 — Gemini API 의존 제거]\n"
    "  MAERSK D/O 좌표 파싱 완성 (ALL PASS)\n"
    "  Packing List 좌표 파싱 완성 (Gemini 불필요)\n"
    "  Picking List _parse_meta 라벨 기반으로 전면 교체\n"
    "  carrier_bl_rule 좌표 모드 추가 (타선사 UI 등록)\n"
    "\n"
    "[Allocation 트랜잭션 개선]\n"
    "  개별 commit 3개 제거 → with transaction() 단일 보호\n"
    "  Phase 주석 9개 추가\n"
    "\n"
    "[MXBG 톤백 무게 계산 원칙 수정]\n"
    "  (LOT 전체 무게 - 1kg) / MXBG 항상 우선\n"
    "  템플릿 단가 덮어쓰기 제거\n"
    "\n"
    "[스캔 탭 전면 개선]\n"
    "  화물 결정 시 picking_table 자동 생성\n"
    "  빠른 스캔 모드 추가 (팝업 없이 즉시 PICKED)\n"
    "  반품등록 → process_return() 호출 (재고 복구 + 이력)\n"
    "  재입고 버튼 신규 추가 (RETURN → AVAILABLE)\n"
    "  연속 스캔 포커스 자동 복귀\n"
    "\n"
    "[반품 로직 버그 3개 수정]\n"
    "  버그2: finalize_return 이중 중량 복구 제거\n"
    "  버그3: finalize_return 트랜잭션 구조 수정\n"
    "  버그4: OUTBOUND 상태 allocation/picking 처리 누락 수정\n"
    "\n"
    "테스트: 407 passed / 4 skipped / 1 failed(기존 기술부채)"
)
