# -*- coding: utf-8 -*-
"""SQM 재고관리 시스템 버전 정보"""

__version__ = "8.5.6"
VERSION = "8.5.6"
VERSION_TUPLE = (8, 5, 6)
RELEASE_DATE = "2026-03-25"
APP_NAME = "SQM 재고관리 시스템"
APP_NAME_EN = "SQM Inventory Management System"
BUILD_DATE = "2026-03-25"
BUILD_NOTE = (
    "v8.5.6 (2026-03-25)\n"
    "PATCH3+4 통합:\n"
    "BUG1: do_mixin.py — MSC DO Vessel 텍스트폴백 추가\n"
    "BUG2: invoice_mixin.py — MSC FA Qty/NetWt/GrossWt 좌표+정규식 수정\n"
    "BUG3: bl_mixin.py — Total Containers/Gross Weight 집계 보강\n"
    "BUG4: picking_list_parser.py — Outbound ID 자동파싱 OUTBOUND_ID_RE\n"
    "PATCH4: packing_mixin.py — import os 추가, SAP No 안전화, 예외처리 강화\n"
    "\n"
    "PATCH1: onestop_inbound.py — Ctrl 다중선택 1회 다이얼로그\n"
    "        자동 분류 금지, 드롭다운 서류 직접 지정\n"
    "        DO 미선택 시 달력 위젯으로 입항일 직접 입력\n"
    "PATCH2: do_mixin.py — MSC 반납기한 정규식 교체\n"
    "        컨테이너별 직접 추출 (XXXX1234567 / / / YYYY-MM-DD)\n"
    "        ContainerInfo.free_time_date 키 추가\n"
    "PATCH2: inbound_mixin.py — con_return 키 불일치 해소\n"
    "        _extract_do_con_return() 다중 경로 참조\n"
    "        가장 늦은 반납일 대표값 적용\n"
    "\n"
    "v8.4.0 FULL (2026-03-24)\n"
    "\n"
    "=== v8.1.6~7 (UI/버그) ===\n"
    "BUG-A: 출고취소 OUTBOUND/SOLD 병행조회\n"
    "BUG-B: _alloc_fallback 차단 제거 (취소버튼 3곳)\n"
    "BUG-C: _safe_call 중복except 수정\n"
    "MOVE: 바코드 스캔이동 탭 신규\n"
    "DB: tonbag_move_log + v8.1.7 마이그레이션\n"
    "\n"
    "=== v8.1.8 (UI 표준화) ===\n"
    "BUG-THEME: 테마 레이스컨디션 수정\n"
    "UI: Spacing.Tab 표준상수 / 탭 헤더 통일\n"
    "UTIL: parse_date_range / build_date_sql\n"
    "PATCH: filedialog parent= 46곳\n"
    "PATCH: 창크기저장 11곳 / 스크롤바 4곳\n"
    "\n"
    "=== v8.1.9 (Footer/대시보드) ===\n"
    "FOOTER: TreeviewTotalFooter 색상 개선\n"
    "FOOTER: 합계Footer 신규 19곳\n"
    "DASHBOARD: 전면개편 3구역 구조\n"
    "  1구역: 재고상태카드 5개\n"
    "  2구역: 정합성신호등+알림패널\n"
    "  3구역: 제품별현황테이블\n"
    "\n"
    "=== v8.2.0 (Phase 1+2 시스템 감사) ===\n"
    "SAFETY: 트랜잭션 빈 except 수정\n"
    "SAFETY: gemini_db_corrector DB 어댑터 주입\n"
    "ARCH: DB 경로 config.DB_PATH 단일화 (7곳)\n"
    "ARCH: files/ 패치 파일 README 명시\n"
    "\n"
    "=== v8.2.1 (Phase 3 성능) ===\n"
    "PERF: N+1 쿼리 최적화 7곳\n"
    "  dashboard 14쿼리→2쿼리 (GROUP BY)\n"
    "  outbound_mixin bulk_cancel pre-fetch\n"
    "  return_mixin pre-fetch\n"
    "  validators 배치 UPDATE\n"
    "  advanced_dialogs pre-fetch\n"
    "  outbound_handlers 2N→2쿼리\n"
    "  inbound_handlers pre-fetch\n"
    "INFRA: query_mixin 공통 메서드 4개 추가\n"
    "\n"
    "=== v8.2.2 (Phase 4+6 코드 품질) ===\n"
    "DEAD: Dead code 27개 제거\n"
    "  구버전 마이그레이션, 미사용 helper,\n"
    "  미사용 AI호출, legacy 메서드,\n"
    "  dashboard stub 12개\n"
    "QUALITY: 운영코드 print() 0개 확인\n"
    "\n"
    "=== v8.2.4 (파서 강화) ===\n"
    "PARSER: D/O Dispatcher 선사 자동 판별 라우팅\n"
    "  MEDU*/MSCU* → MSC, MAEU*/MRKU* → Maersk\n"
    "PARSER: do_mixin SQM DOData 통합 반환\n"
    "PARSER: msc carrier_templates 좌표 파서\n"
    "DB: parsing_log 통계 테이블 신규\n"
    "HOTFIX: auto_tooltip.py NameError 수정\n"
    "  _patched_menu_init 미정의→클로저 삽입\n"
    "\n"
    "=== v8.3.0 (Phase 9~11 감사/운영) ===\n"
    "NEW: audit_helper.py — LOT 처리 이력 감사 로그 중앙화\n"
    "  INBOUND/OUTBOUND/RESERVED/RETURN/LOT_UPDATE/LOT_DELETE\n"
    "  inbound_mixin, outbound_mixin, crud_mixin, return_mixin 연동\n"
    "NEW: migration_manager.py — Alembic 스타일 DB 마이그레이션\n"
    "  schema_version 테이블 / 멱등성 보장 (IF NOT EXISTS)\n"
    "  db_schema_mixin 연동 — 앱 시작 시 자동 버전 동기화\n"
    "NEW: error_notifier.py — 에러 이메일 알림 모듈\n"
    "  정합성 오류 / 파싱 실패 알림\n"
    "NEW: daily_report.py — 일별 처리 건수·무게 자동 리포트\n"
    "  엑셀 저장 + 이메일 전송 + 스케줄러 연동\n"
    "ALLOC: allocation_approval_dialog 승인/반려 audit_log 기록\n"
    "ALLOC: workflow_status SQL 문자열→상수 교체\n"
    "DASH: 파싱 실패율 경고 (최근 7일 30% 초과 시)\n"
    "DASH: Allocation 승인 대기 배지\n"
    "TEST: test_v830_phase9_11.py 30개 (P9A~P11)\n"
    "\n"
    "=== v8.3.1 (UX 즉시 출고) ===\n"
    "UX: 재고 탭 우클릭 → '즉시 출고 (원스톱)' 메뉴 추가\n"
    "  inventory_tab 우클릭 컨텍스트 메뉴 확장\n"
    "  onestop_outbound initial_lot_no 자동 채우기\n"
    "UX: 고객사 콤보박스 + Sale Ref 빠른 입력 (출고)\n"
    "FIX: gemini_db_corrector db_adapter 우선, sqlite3 fallback\n"
    "PERF: validators N+1 → 배치 pre-fetch (BL free_time)\n"
    "\n"
    "=== v8.3.2 (출고 UX 강화) ===\n"
    "UX: onestop_outbound 고객사 빠른 선택 UI\n"
    "  콤보박스 선택 시 붙여넣기 란 자동 업데이트\n"
    "\n"
    "=== v8.3.3 (PRO DARK 테마) ===\n"
    "THEME: ui_constants PRO DARK 테마 전면 재설계\n"
    "  Flexport/Linear/Vercel 디자인 기준\n"
    "  Slate-900 배경 + Cyan-400 강조 + 색맹 대응\n"
    "  Status 행 배경색 개선 (채도↓ 명도차↑)\n"
    "UX: onestop_inbound 상단 진행 단계 표시 (Flexport 스타일)\n"
    "  4단계: 서류선택→파싱실행→결과확인→DB저장\n"
    "MENU: menu_registry 물류 앱 기준 재편\n"
    "  핵심 동작(PDF입고/엑셀입고) 우선, 관리 기능 후단\n"
    "\n"
    "=== v8.4.0 (Phase 8 웹 계획) ===\n"
    "DOC: Phase8_Web_개발계획서.md\n"
    "  NiceGUI 웹 조회 화면 확정 (React B안 폐기)\n"
    "  tkinter 병행 + NiceGUI 읽기전용 조회\n"
    "  sqm_web/ 뼈대 존재 (theme.py 100%)\n"
    "FIXTURE: sqm_scenario_data.py 테스트 데이터 확장\n"
    "\n"
    "=== v8.4.2 (템플릿 매핑 핫픽스) ===\n"
    "FIX-SAP: T03 Manual Inbound SAP NO 앞자리 0 소실 버그 수정\n"
    "  import_handlers + inbound_handlers _read_inbound_excel_with_header\n"
    "  dtype={SAP NO:str, LOT NO:str, BL NO:str, CONTAINER:str} 적용\n"
    "FIX-REG: column_registry 한글 alias 추가\n"
    "  arrival_date += '입고일', '입항일'\n"
    "  outbound_date += '출고일'\n"
)
