# -*- mode: python ; coding: utf-8 -*-
# SQM v864.4 PyInstaller spec (auto-generated by scripts/build_exe.py)

from PyInstaller.utils.hooks import collect_all, collect_submodules

# ──────────────────────────────────────────────
# 1. 데이터 파일 (frontend, config 등)
# ──────────────────────────────────────────────
datas = [
    ('frontend', 'frontend'),
    ('config.py', '.'),
    ('config_logging.py', '.'),
    ('config_sql.py', '.'),
]

# ──────────────────────────────────────────────
# 2. Hidden imports — PyInstaller 가 자동 탐지 못하는 서브모듈
# ──────────────────────────────────────────────
hiddenimports = []
for pkg in ('engine_modules', 'features', 'parsers', 'backend'):
    hiddenimports += collect_submodules(pkg)

# 추가 런타임 모듈
hiddenimports += [
    'fastapi',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.wsproto_impl',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.http.httptools_impl',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'pandas',
    'openpyxl',
    'webview',
    'webview.platforms.winforms',
    'clr',
    'clr_loader',
]

# ──────────────────────────────────────────────
# 3. collect_all — 필수 바이너리/데이터 포함 (pandas, openpyxl, webview)
# ──────────────────────────────────────────────
binaries = []
for pkg in ('pandas', 'openpyxl', 'webview'):
    try:
        pd, pb, ph = collect_all(pkg)
        datas += pd
        binaries += pb
        hiddenimports += ph
    except Exception as _e:
        print(f'[spec] collect_all {pkg} 실패 (무시): {_e}')

# ──────────────────────────────────────────────
# 4. Analysis
# ──────────────────────────────────────────────
a = Analysis(
    ['main_webview.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter.test',
        'pytest',
        'black',
        'IPython',
        'jupyter',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

# ──────────────────────────────────────────────
# 5. EXE (onefile mode)
# ──────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SQM_v864_4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,             # UPX 압축 안 함 (Windows Defender 오탐 방지)
    runtime_tmpdir=None,
    console=False,         # --noconsole (frozen stdout 은 main_webview.py 에서 처리)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'frontend/favicon.ico' if __import__('os').path.exists('frontend/favicon.ico') else None,
)
